### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by sprucial** [ryexley/sycamore#2]
Hi Ryan,

I couldn't find a licence file or license statement for Sycamore. I note your other projects are MIT licensed but need some kind of documentation to show the licence for my project. Would it be possible for you to add something? Thanks!

**Comment by ryexley** [comment]
@sprucial - That is my oversight, sorry. Thats a good idea, and yes, I will get a license file added to the repo. It *is* in fact under an MIT license, which I believe is indicated in the banner comments at the top of the files in `dist`, but it would still be a good idea to get a license file added. Thanks for your interest.

**Comment by sprucial** [comment]
Sorry Bob, was also looking at some of Ryan's projects hence calling you the wrong name! Thanks for the update.

**Comment by ryexley** [comment]
No problem...Ryan contributed much to this project as well. Thanks for your interest.

**Comment by ryexley** [comment]
@sprucial I _finally_ added a LICENSE file to the repository as you requested. So sorry it took me this long to finally get to doing that.
